package com.capstone.dfms.mappers;

import com.capstone.dfms.models.HealthRecordEntity;
import com.capstone.dfms.models.IllnessDetailEntity;
import com.capstone.dfms.requests.HealthRecordExcelRequest;
import com.capstone.dfms.requests.HealthReportRequest;
import com.capstone.dfms.requests.IllnessDetailUpdateRequest;
import org.mapstruct.*;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")
public interface IHealthReportMapper {
    IHealthReportMapper INSTANCE = Mappers.getMapper(IHealthReportMapper.class);

    @Mapping(source = "cowId", target = "cowEntity.cowId")
    HealthRecordEntity toModel(HealthReportRequest request);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(source = "cowId", target = "cowEntity.cowId")
    void updateEntityFromDto(HealthReportRequest dto, @MappingTarget HealthRecordEntity entity);

    @Mapping(target = "healthRecordId", ignore = true) // Auto-generated by DB
    @Mapping(target = "cowEntity.name", source = "cowName") // Set manually in service
    @Mapping(target = "status", expression = "java(request.getHealthRecordStatus())") // Convert String -> Enum
    @Mapping(target = "period", expression = "java(request.getCowStatus())") // Convert String -> Enum
    @Mapping(target = "reportTime", expression = "java(java.time.LocalDateTime.now())") // Set current timestamp
    @Mapping(target = "weight", ignore = true) // Optional, ignore if not needed
    HealthRecordEntity toModel(HealthRecordExcelRequest request);
}
