services:
  dfms-backend:
    image: capstone/dfms:latest
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db_dfms
      MYSQL_PORT: 3306
      MYSQL_USER: dairyfarm2024
      MYSQL_PASSWORD: dairyfarm2003
      MYSQL_DATABASE: dfms
      VERIFY_URL: http://34.124.196.11:8080/api/v1/users/verify
    depends_on:
      - db_dfms
    volumes:
      - /root/images:/app/uploads

  db_dfms:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SWD392
      MYSQL_DATABASE: dfms
      MYSQL_USER: dairyfarm2024
      MYSQL_PASSWORD: dairyfarm2003
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
