server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:dairyfarm}?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n/messages
    encoding: UTF-8
    always-use-message-format: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Ho_Chi_Minh
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 796302756667-v8k7e9vj907llfj9nrucos35ndqll7i5.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: https://api.dairyfarmfpt.website/login/oauth2/code/google


app:
  fpt:
    api_key: SNaSqItaLhEtrgXslChU3EzBqhyPjDKE
    ocr_url: https://api.fpt.ai/vision/idr/vnm
  firebase:
    service-account-file: ${FIREBASE_CONFIG:{"type":"service_account","project_id":"dfms-268e0","private_key_id":"5f06c2969800564c3bb8035593b025b0b2f00249","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0SYCA4HkhM5zK\ng6SIZhzYw2IlSAeLlnWwqfj6i5ofxKuGrO+2yPM1656vwOwZXelkWM+MU3dRtZLf\nwHNL5G+dFVmur5bK5PRfPhtToqHr5zOzjDFFNCehPKlaLbXLRsmO9/81mlu2Is0i\nCK8pLlKt/Dv0ppWJB1r89c7H3YtNrcKlnZ1/1Og0jja3qlklPUYQsC8nB6sAc7Yf\n0OV61W2FnTvSW9G2VjGy+jONfoBddysEsI18hHJMjXVY7K+R2h+bnWjHP0dt21+t\nKa+5WoS+2RdwKLz04WLx3J3Au5iX1wPcgfvjKTRUsSCKaewvr0ts+tGz62+SCqPJ\nqYZgkx/JAgMBAAECggEACOHxNDuH3eN1QQLgHAqAUKUjV6GXO5QMohX+l77BxHk6\nZHHuhDOdstIN0rkSeN2umak76patk44UZmezPPGl/STEf/Qtqm5bsVPPevarLyk7\ndYgKYM9xxc9feBTpKgXuEtgnQxMWNZPv37jy6ZH02v0i0BcJpl0OKTxY9Vh2D1Wt\nD95RfQTWdO4/6baknaYrgbAyE/XWGupbKQpN+AqMPF9kDZMmtPfaER2Fzca0kfGC\nyZRzIy9TD8BTBLlmEB7yNemOkMgKhb25XQRN/62LgdsKvLze5gqH68ywoFcw9mtB\nqiikMq00pJDMMP3VoD8BB7odvQKIznuCkWsZ5fPKrQKBgQDkDwlyJ9CPw6ZqcvOy\naVZlwe8mScyPE2mn5aGSY/BHHUAp9LnphCkeRRZeH5gYz/G5oDOQM9GcJyv9Y/Zm\nmNPUPI+agSK09uwn+aS4PwYyst/IbYmgTU1XNtfd0mVX3ucLCZ/wKitQ2twxbG3M\nN9Jw7L4JLORtMRsy5KH1aGo+5QKBgQDKYCEDuizEB7yEmoxoOmUGx2gFyZx6nPiD\nIUXmTEloqaKKDJllwCWg41wt7sX8cB7qgGmilfNjiGjziPY077tfqsFzRy1sYe3D\nLBVOwPBn1WhXOLkzdJPMkEW7VYq1wj9lDi2V+niYzkTGEL0W+aHeeXiPsAXOjd0Q\nLu1u8eWrFQKBgFehJ4IDpnH3PZSdguJE83u6HwhZRw6a6PgolgLH/+Vzado1PNJr\ng9krtsKH5Utza3BmDCoWny4fJxoANQeLJanhc1Rs1kcuseNSW2aoYNtOPAqpfD5q\nNZOTcTK8y1AOSDzHf/sqWOaCkiUzgqT7thLKBONFqqgCPG87xrejXV+5AoGBAKjP\nNNrSEoNWXLdT32kVxK256hhhy0gv5dAkEhV/bwCB99YlmlNYy0qAPKUH9liTAgbk\nJLl9UW+mGr2CcrVHf8nWOtW4+rfcnCLgg8mUgTRrvER9SWcViC/r7G7OdQ0WQiE+\niWIAc1YrQQzia4hdpNtaAeoBj2ZzyYG1U1LnLofdAoGAICwfXGkSPbpL0vvGspKm\n26VAvQjZNtJlxnTo4aT7VZgBZqwLki4IGTLk35EQmrf68lwjn7xYwm5PnA/bfbgV\nFA1HWdln4yV320VOi/luOc9KkjiOdM10bB9zByjnCuKMzwoS3zMFjsjaaJ+NrSdW\nGe2hRMbGPxah1wabpw7nGb4=\n-----END PRIVATE KEY-----\n","client_email":"firebase-adminsdk-fbsvc@dfms-268e0.iam.gserviceaccount.com","client_id":"115530070335163499477","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40dfms-268e0.iam.gserviceaccount.com","universe_domain":"googleapis.com"}}
  fe:
    verify_url: ${VERIFY_URL:http://localhost:8080/api/v1/users/verify}
    forgot_password_url: ${FORGOT_PASSWORD_URL:http://localhost:8080/api/v1/users/setpassword}
    path: http://localhost:5173
  cors:
    allowedOrigins: http://localhost:4176,http://localhost:4200,http://34.124.196.11:8080,https://34.124.196.11,https://34.124.196.11
  api:
    version:
      v1: /api/v1
  openapi:
    dev-url: http://localhost:${SERVER_PORT:8080}
    prod-url: https://api.dairyfarmfpt.website
  auth:
    tokenSecret: T04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    refreshTokenExpirationMsec: 864000000  # 10 days
    accessTokenExpirationMsec: 1800000 # 15 minutes
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:dairyfarmfpt2024@gmail.com}
    password: ${EMAIL_PASSWORD:zczn gpul doso imfo}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
